#!/bin/sh

version=`head -n 1 /opt/victronenergy/version`

echo Detected Venus version $version

guiDir=/data/TankRepeater/GuiUpdates
qmlDir=/opt/victronenergy/gui/qml

# select GUI file set based on Venus version
case $version in
        v2.33)
                guiVer='2.33'
                ;;
        v2.42|v2.51|v2.52|v2.53|v2.60~14|v2.60~15|v2.60~16)
                 guiVer='2.42'
                ;;
        v2.60~19)
                guiVer='2.60~19'
                ;;
        *)
                guiVer='none'
                ;;
esac

if [ $guiVer == 'none' ]; then
    echo WARNING no GUI files for Venus $version
    echo No GUI files will be changed
    echo You must manually merge GUI changes in these files:
    echo "   OverviewMobile.qml"
    echo "   TileTank.qml"
else
    echo Preserving original GUI files

    srcFile=OverviewMobile.qml
    destFile=$srcFile.orig
    if [ -f "$destFile" ]; then
        echo $destFile exists from previous repeater installation and will not changed
        echo $srcFile will be overwritten
    else
        echo $srcFile saved as $destFile
        mv $qmlDir/$srcFile $qmlDir/$destFile
    fi

    srcFile=TileTank.qml
    destFile=$srcFile.orig
    if [ -f "$destFile" ]; then
        echo $destFile exists from previous repeater installation and will not changed
        echo $srcFile will be overwritten
    else
        echo $srcFile saved as $destFile
        mv $qmlDir/$srcFile $qmlDir/$destFile
    fi

    echo Copying updated GUI files from GuiUpdates$guiVer
    cp $guiDir$guiVer/* $qmlDir
fi

echo Starting repeater processes - ignore any errors reported
rm -f /service/SeeLevelRepeater
ps |grep See |grep -v grep|awk '{print $1}' | xargs kill

ln -s /data/TankRepeater/SeeLevelRepeater /service

echo Waiting 10 seconds for Repeater to start
sleep 10
echo Restarting GUI
killall gui

echo SeeLevel Repeater install complete

