#!/bin/sh

version=`head -n 1 /opt/victronenergy/version`

echo Detected Venus version $version

guiDir=/data/TankRepeater/GuiUpdates
qmlDir=/opt/victronenergy/gui/qml

echo
echo This script will install the SeeLevel tank repeater and update GUI files
echo to hide the Seelevel tank since the reported tank keeps changing
echo
echo -n "Do you wish to install the enhanced OverviewMobile page: y/n :"
read enhancedOverview

echo
while :
do
    echo -n "Do you wish to update Tank Tiles: y/n/? :"
    read tileUpdate
    
    if  [ $tileUpdate == 'y' ] || [ $tileUpdate == 'n' ]; then
        break
    else
        echo The updated TileTank.qml provides the following changes:
        echo Bar text turns red and indicates "NO RESPONSE" for sensor connection errors
        echo Color of bar turns red on limits instead of blinking
        echo Color of bar text turns red when bar lenght is too short to be seen
        echo If space is limited, bar graph height and associated text are reduced
        echo Added custom tank name
    fi
done
echo
echo Updating GUI files
srcFile=OverviewMobile.qml
destFile=$srcFile.orig
if [ -f $qmlDir/$destFile ]; then
    echo $destFile exists from previous repeater installation
    echo and will not be touched
else
    echo Existing $srcFile will be moved to $destFile
    mv $qmlDir/$srcFile $qmlDir/$destFile
fi

if [ $enhancedOverview == 'y' ]; then
    echo Replacing $srcFile with ennhanced OverviewMobile page
    cp $guiDir/Enhanced$srcFile $qmlDir/$srcFile
    cp $guiDir/SystemReasonText.qml /$qmlDir
else
    echo Modifying $srcFile based on $destFile
    sed -f $guiDir/sedCommands $qmlDir/$destFile > $qmlDir/$srcFile
fi

if  [ $tileUpdate == 'y' ]; then
    srcFile=TileTank.qml
    destFile=$srcFile.orig
    if [ -f $qmlDir/$destFile ]; then
        echo $destFile exists from previous repeater installation and will not changed
        echo $srcFile will be overwritten
    else
        echo $srcFile saved as $destFile
        mv $qmlDir/$srcFile $qmlDir/$destFile
    fi

    cp $guiDir/TileTank.qml $qmlDir
else
    echo TileTank.qml not changed
fi

echo Starting repeater processes - ignore any errors reported
rm -f /service/SeeLevelRepeater
ps |grep SeeLevelRepeater |grep -v grep|awk '{print $1}' | xargs kill

ln -s /data/TankRepeater/service /service/SeeLevelRepeater

echo Waiting 10 seconds for Repeater to start
sleep 10
echo Restarting GUI
killall gui

echo SeeLevel Repeater install complete

