#!/bin/sh

# this script sets up (or deactivates/removes) the SeeLevel Repeater
# it is designed to run on a unix host or directly on the Venus system

# file check that works locally and remotly via ssh
fileExists ()
{
        if [ -z "$commandPreamble" ]; then
                return $(test -e $1)
        else
                return $($commandPreamble test -e $1)
        fi
}

# closes shared ssh connection
sshRelease ()
{
    if [ ! -z "$commandPreamble" ]; then
        ssh -q -o ControlPath=$controlPath -O exit root@$ipAddr
    fi
}

scriptDir=$(dirname "$0")
repeaterDir=/data/TankRepeater
guiDir=$repeaterDir/GuiUpdates
qmlDir=/opt/victronenergy/gui/qml
srcOmFile=OverviewMobile.qml
destOmFile=$srcOmFile.orig
srcTankFile=TileTank.qml
destTankFile=$srcTankFile.orig
filesToCopy='SeeLevelRepeater.py ext GuiUpdates ReadMe service setup rc.SeeLevel'

actionText=""
overviewText=""
tankTileText=""
delteteLogText=""


# display innitial message if no command line arguments
if [ -z $1 ]; then
    echo
    echo The SeeLevel tank repeater provides a stable display for
    echo NMEA2000 tank systems that report multiple tanks.
fi

# collect any command line parameters
ipAddr=''
action=''
enhancedOverview=''
enhancedTankTile=''
deleteLogs=''
while [ ! -z $1 ]
do
    case $1 in
        ip)
            shift
            ipAddr=$1
            ;;
        activate | a)
            action='a'
            ;;
        reactivate | r)
            action='r'
            ;;
        install | in | i)
            action='i'
            ;;
        deactivate | d)
            action='d'
            ;;
        uninstall | u)
            action='u'
            ;;
        log | l)
            action='l'
            ;;
        copy | c)
            action='c'
            ;;
        quit | q)
            action='q'
            ;;
        eo)
            shift
            enhancedOverview=$1
            ;;
        et)
            shift
            enhancedTankTile=$1
            ;;
        dl)
            shift
            deleteLogs=$1
            ;;
        *)
            echo warning: unrecognized parameter $1
    esac
    shift
done

#prompt for parameters not provided on the command line

if [ -z $action ]; then
    echo
    echo "This script will do the following:"
    echo "  Activate (a) updates the GUI files and starts the repeater"
    echo "  Reactivate (r) Activates based on GUI options specified on for last activate"
    echo "  Deactivate (d) stops the repeater, exposing the SeeLevel tank in the tanks column"
    echo "  Uninstall (u) deactivates, restores GUI files to stock and remove all repeater files"
    echo "  Quit (q) without further action"
    echo "  Display Log (l) outputs the last 100 lines of the Repeater log"
    echo " additional choices when running on host"
    echo "  Copy (c) copies file from host to Venus and exits"
    echo "  Install (i) Copy then Activate"
    echo
fi
while [ -z $action ] || ! ( [ $action == 'a' ] || [ $action == 'r' ] || [ $action == 'd' ] || [ $action == 'u' ] || [ $action == 'q' ]\
            || [ $action == 'l' ]|| [ $action == 'i' ] || [ $action == 'c' ] )
do
    /bin/echo -n "Choose an action from the list above: "
    read action
done

if [ $action == 'q' ]; then
    sshRelease
    exit
fi

if [ $action == 'a' ] || [ $action == 'i' ]; then
    actionText="Activating repeater"

    # prompt for remaining activate parameters
    if [ -z $enhancedOverview ]; then
        echo
        echo "The Enhanced overview includes the following changes:"
        echo "  1) Hides the SeeLevel tank (changing values)"
        echo "  2) Tiles are arranged to more cloesly follow the power flow through the system"
        echo "  3) Voltage, current and frequency values are added to the AC in and out tiles"
        echo "  4) Battery remaining time is added to the Battery tile"4
        echo "  5) ESS reason codes are replaced with a text version to make them more meaningful"
        echo "  6) ESS reason text and other notifications are combined into a single "marquee" line"
        echo "  7) The pump switch is hidden unless the Venus relay is configured for pump control"
        echo "  8) AC Mode switch includes INVERTER ONLY mode"
        echo
    fi
    while [ -z $enhancedOverview ] || ! ( [ $enhancedOverview == 'y' ] || [ $enhancedOverview == 'n' ] )
    do
        /bin/echo -n "Do you wish to install the Enhanced Mobile Overview Page? (y/n): "
        read enhancedOverview
    done

    if [ -z $enhancedTankTile ]; then
        echo
        echo "Tank Tile enhancements:"
        echo "  1) The updated TileTank.qml provides the following changes:"
        echo "  2) Bar text turns red and indicates NO RESPONSE for sensor connection errors"
        echo "  3) Color of bar turns red on limits instead of blinking"
        echo "  4) Color of bar text turns red when bar lenght is too short to be seen"
        echo "  5) If space is limited, bar graph height and associated text are reduced"
        echo "  6) Added custom tank name"
        echo
    fi
    while [ -z $enhancedTankTile ] || ! ( [ $enhancedTankTile == 'y' ] || [ $enhancedTankTile == 'n' ] )
    do
        /bin/echo -n "Do you wish to install the OPTIONAL Tank Tile changes (y/n): "
        read enhancedTankTile
    done
fi

# do not delete logs for some actions
if [ -z $deleteLogs ] && ( [ $action == 'r' ] || [ $action == 'c' ] || [ $action == 'q' ] || [ $action == 'l' ] ); then
    deleteLogs='n'
fi

# prompt for deleting logs if not previously specified
echo
while [ -z $deleteLogs ] || ! ( [ $deleteLogs == 'y' ] || [ $deleteLogs == 'n' ] )
do
    /bin/echo -n "Do you wish to remove log files (y/n): "
    read deleteLogs
done


# check to see if script is running on host or Venus device
# running on Venus device
if [ -f /opt/victronenergy/version ]; then
    version=$(head -n 1 /opt/victronenergy/version)
    echo running on Venus - version $version
    commandPreamble=""

# running on host
else
    # persist at getting a valid IP address
    while [ -z $ipAddr ]
    do
        # try to get last one from file
        if [ -f "$scriptDir/venusIp" ]; then
            ipAddr=$( cat "$scriptDir/venusIp")
        fi
        if [ ! -z $ipAddr ]; then
            /bin/echo -n "Enter a new Venus IP address (cr) to use $ipAddr: "
            read answer
            if [ ! -z $answer ]; then
                ipAddr=$answer
            fi
        else
            /bin/echo -n "Enter the IP address of the Venus OS device: "
            read ipAddr
        fi
        if [ -z $ipAddr ]; then
            continue
        fi
        # make innitial ssh connection and set up ssh sharing
        controlPath=~/.ssh/%r@%h:%p
        commandPreamble="ssh -o ControlPath=$controlPath root@$ipAddr"
        # close a previous shared ssh connection if any
        sshRelease
        # attempt a new connection
        version=$($commandPreamble -o ControlMaster=yes -o ControlPersist=5m head -n 1 /opt/victronenergy/version)
        if [ -z $version ]; then
            echo $ipAddr does not appear to be a Venus device
            ipAddr=""
        fi
    done

    echo connected to remote Venus version $version at $ipAddr
    # save IP address for future use
    echo $ipAddr > "$scriptDir/venusIp"

    # assume we'll copy and continue
    copyToVenus='y'
    continueOnVenus='y'
    # don't continue if uninstalling and repeater never installed
    if [ $action == 'u' ]; then
        copyToVenus='n'
        # don't continue if repeater was never installed
        if ! fileExists $repeaterDir ; then
            continueOnVenus='n'
            echo no files to delete
        fi
    # don't continue if just copying
    elif [ $action == 'c' ]; then
        continueOnVenus='n'
    # display log command executed on host - don't copy or continue
    elif [ $action == 'l' ]; then
        copyToVenus='n'
        continueOnVenus='n'
    fi

    if [ $copyToVenus == 'y' ]; then
        if ! fileExists $repeaterDir ; then
            echo creating TankRepeater directory
            $commandPreamble mkdir $repeaterDir
        fi
        echo copying Repeater files from host to Venus
        scp -rpq -o ControlPath=$controlPath $filesToCopy root@$ipAddr:$repeaterDir
    fi

    # continue setup on Venus device
    if [ $continueOnVenus == 'y' ]; then
        echo contining setup on Venus ...
        $commandPreamble $repeaterDir/setup $action eo $enhancedOverview et $enhancedTankTile dl $deleteLogs
    fi
fi

# just display log and exit - runs from host or Venus !
if [ $action == 'l' ]; then
    $commandPreamble tail -100 /var/log/SeeLevelRepeater/current | $commandPreamble tai64nlocal
    sshRelease
    exit
fi

# exit here if running on host
if [ "$commandPreamble" ]; then
    sshRelease
    exit
fi


# the remainder of this script runs ONLY on the Venus device
# we get here from the ssh call to setup above
# all parameters are passed to setup so all prompts for user input are bypassed

# if reactivating, pull GUI update parameters from flag files
if [ $action == 'r' ]; then
    echo reactivating repeater
    actionText="Reactivating repeater"
    if fileExists $repeaterDir/useEnhancedOverview ; then
        enhancedOverview='y'
    else
        enhancedOverview='n'
    fi
    if fileExists $repeaterDir/useEnhancedTankTile ; then
        enhancedTankTile='y'
    else
        enhancedTankTile='n'
    fi
fi

# stop repeater - it will be restarted later if appropriate
# all Repeater functionality is deactivated but any GUI modifications remain in place
echo stopping repeater processes
rm -f /service/SeeLevelRepeater
ps -l | grep SeeLevelRepeater | grep multilog | awk '{print $4}' | xargs kill > /dev/null 2>&1
ps | grep SeeLevelRepeater | grep -v grep  | awk '{print $1}' | xargs kill > /dev/null 2>&1


# if uninstalling, remove existing Repeater files
if [ $action == 'u' ]; then
    echo "removing all Repeater files (if any)"
    rm -rf $repeaterDir
fi

if [ ! -z $deleteLogs ] && [ $deleteLogs == 'y' ]; then
    echo removing log files
    delteteLogText="Log emptied"
    rm -Rf /var/log/SeeLevelRepeater
fi

# remove old installer files if present
if fileExists $repeaterDir/install ; then
    echo "removing obsolete install file"
    rm -f $repeaterDir/install
fi
if fileExists $repeaterDir/rc.local ; then
    echo "removing obsolete rc file"
    rm -f $repeaterDir/rc.local
fi

if [ $action == 'a' ] || [ $action == 'r' ] || [ $action == 'i' ]; then
    # save original GUI files
    if [ ! -z $enhancedOverview ] && [ $enhancedOverview == 'y' ]; then
        if fileExists $qmlDir/$destOmFile ; then
            echo $destOmFile exists - not changed
            overviewText="Enhanced Overview"
        else
            echo existing $srcOmFile saved as $destOmFile
            mv $qmlDir/$srcOmFile $qmlDir/$destOmFile
        fi
        echo Installing Ennhanced Mobile Overview
        cp $guiDir/Enhanced$srcOmFile $qmlDir/$srcOmFile
        cp $guiDir/SystemReasonMessage.qml /$qmlDir
    else
        if fileExists $qmlDir/$destOmFile ; then
            echo $destOmFile exists - not changed
        else
            echo existing $srcOmFile saved as $destOmFile
            mv $qmlDir/$srcOmFile $qmlDir/$destOmFile
            rm -f $qmlDir/SystemReasonMessage.qml
        fi
        echo Modifying $srcOmFile based on $destOmFile
        sed -f $guiDir/sedCommands $qmlDir/$destOmFile > $qmlDir/$srcOmFile
    fi
    # install enhanced Tank Tile
    if  [ ! -z $enhancedTankTile ] && [ $enhancedTankTile == 'y' ]; then
        echo Installing updated Tank Tile
        tankTileText="Enhanced Tank"
        if fileExists $qmlDir/$destTankFile ; then
            echo $destTankFile exists - not changed
            echo $srcTankFile overwritten
        else
            echo $srcTankFile saved as $destTankFile
            mv $qmlDir/$srcTankFile $qmlDir/$destTankFile
        fi
        cp $guiDir/$srcTankFile $qmlDir
    # restore origial tank file if it exists
    elif fileExists $qmlDir/$destTankFile ; then
        echo $destTankFile exists, making it active again
        mv $qmlDir/$destTankFile $qmlDir/$srcTankFile
    else
        echo $srcTankFile not changed
    fi

    # setup for reactivate - save GUI choices and install reactivate code in rc.local
    $commandPreamble touch $repeaterDir/reactivate
    if [ ! -z $enhancedOverview ] && [ $enhancedOverview == 'y' ]; then
        touch $repeaterDir/useEnhancedOverview
    else
        rm -f $repeaterDir/useEnhancedOverview
    fi
    if [ ! -z $enhancedTankTile ] && [ $enhancedTankTile == 'y' ]; then
        touch $repeaterDir/useEnhancedTankTile
    else
        rm -f $repeaterDir/useEnhancedTankTile
    fi

    if ! fileExists /data/rc.local ; then
        echo creating /data/rc.local
        cp $repeaterDir/rc.SeeLevel /data/rc.local
    else
        if [ $(grep -c endSeeLevel /data/rc.local) == 0 ]; then
            echo adding repeater reactivate to /data/rc.local
            sed '1,/end\ intro/d' $repeaterDir/rc.SeeLevel >> /data/rc.local
        fi
    fi
    
    startRepeater='y'
else
    echo
    echo unhiding SeeLevel dBus service
    dbus -y com.victronenergy.settings /Settings/Devices/TankRepeater/SeeLevelService SetValue "" > /dev/null 2>&1
    if [ action == 'd' ]; then
        echo leaving GUI modifications in place
        actionText="Deactivating repeater"
    else
        actionText="Uninstalling repeater"
    fi

    # make sure repeater isn't reactivated
    rm -f  $repeaterDir/reactivate
    # uninstall - restore GUI (files were removed above)
    if [ $action == 'u' ]; then
        echo
        echo restoring oritinal Mobile Overview and Tank Tile files
        if fileExists $qmlDir/$destOmFile ; then
            echo $destOmFile exists, making it active again
            mv $qmlDir/$destOmFile $qmlDir/$srcOmFile
        else
            echo $destOmFile does not exist - $srcOmFile not changed
        fi
        if fileExists $qmlDir/$destTankFile ; then
            echo $destTankFile exists, making it active again
            mv $qmlDir/$destTankFile $qmlDir/$srcTankFile
        else
            echo $destTankFile does not exist - $srcTankFile not changed
        fi
        rm -f $qmlDir/SystemReasonMessage.qml
    fi
    startRepeater='n'
fi

# add a message to the Repeater log regarding this setup
echo ++ setup: "$actionText $overviewText $tankTileText $delteteLogText" | tai64n >> /var/log/SeeLevelRepeater/current

if [ $startRepeater == 'y' ]; then
    echo starting repeater process
    ln -s $repeaterDir/service /service/SeeLevelRepeater

    echo waiting 10 seconds for Repeater to start
    sleep 10
fi



echo Restarting GUI
killall gui
