#!/bin/sh

echo This script will remove the SeeLevel repeater and restore GUI files

read -p "Do you wish to continue: (y/n): " answer

if test $answer != 'y'; then
	exit
fi

echo Restoring GUI files

qmlDir=/opt/victronenergy/gui/qml

destFile=$qmlDir/OverviewMobile.qml
srcFile=$destFile.orig
if [ -f "$srcFile" ]; then
	echo Restoring $srcFile from $destFile
	mv $srcFile $destFile
else
	echo no $srcFile to restore from
fi

destFile=$qmlDir/TileText.qml
srcFile=$destFile.orig
if [ -f "$srcFile" ]; then
	echo Restoring $srcFile from $destFile
	mv $srcFile $destFile
else
	echo no $srcFile to restore from
fi

echo Unhiding SeeLevel tanks
dbus -y com.victronenergy.settings /Settings/Devices/TankRepeater/SeeLevelService SetValue ""

echo Killing repeater processes and restarting gui - ignore any errors reported
rm -f /service/SeeLevelRepeater
ps |grep SeeLevelRepeater |grep -v grep|awk '{print $1}' | xargs kill
killall gui

echo Removing Repeater files from /data
echo Repeater log /var/log/SeeLevelRepeater retained for future reference
rm -rf /data/TankRepeater

echo SeeLevel Repeater uninstall complete
